<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>FOVFix</AssemblyName>
    <Description>Fixes EFT FOV (removes FOV decrease when ADS)</Description>
    <Version>4.0.1</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
	  <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
	  <CopyProjectReferencesToOutputDirectory>false</CopyProjectReferencesToOutputDirectory>
  </PropertyGroup>

	<Target Name="Build Cleanup" AfterTargets="Build">
		<Delete Files="$(OutDir)$(AssemblyName).pdb" />
		<Delete Files="$(OutDir)$(AssemblyName).deps.json" />
	</Target>

	<ItemGroup>
    <Reference Include="spt-reflection">
        <HintPath>D:\ref41\spt-reflection.dll</HintPath>
      <Private>false</Private>
    </Reference>
	<Reference Include="ItemComponent.Types">
        <HintPath>D:\ref41\ItemComponent.Types.dll</HintPath>
	  <Private>false</Private>
	</Reference>
    <Reference Include="Comfort">
        <HintPath>D:\ref41\Comfort.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
        <HintPath>D:\ref41\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
	<Reference Include="UnityEngine">
        <HintPath>D:\ref41\UnityEngine.dll</HintPath>
	  <Private>false</Private>
	</Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
        <HintPath>D:\ref41\UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
        <HintPath>D:\ref41\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
	<Reference Include="UnityEngine.UIModule">
        <HintPath>D:\ref41\UnityEngine.UIModule.dll</HintPath>
	  <Private>false</Private>
	</Reference>
	<Reference Include="Sirenix.Serialization">
        <HintPath>D:\ref41\Sirenix.Serialization.dll</HintPath>
	  <Private>false</Private>
	</Reference>
        
	<Reference Include="RealismMod">
        <HintPath>D:\ref41\RealismMod.dll</HintPath>
	  <Private>false</Private>
	</Reference>
	<Reference Include="Unity.Postprocessing.Runtime">
        <HintPath>D:\ref41\Unity.Postprocessing.Runtime.dll</HintPath>
	  <Private>false</Private>
	</Reference>
    <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
    <PackageReference Include="BepInEx.Core" Version="5.*" />
    <PackageReference Include="BepInEx.PluginInfoProps" Version="1.*" />
  </ItemGroup>
  
  <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2" PrivateAssets="all" />
  </ItemGroup>
</Project>
